version: '3.8'

services:
  app-spring:
    build:
      context: .
    container_name: mi-spring-app
    ports:
      - "8080:8080"
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge