networks:
  loki-net:
    driver: bridge

services:
  app-spring:
    build:
      context: ./
    container_name: mi-spring-app
    volumes:
      - ./logs:/app/logs # Carpeta donde tu aplicación Spring Boot creará el archivo app.log
    ports:
      - "8080:8080"
    networks:
      - loki-net

  loki:
    image: grafana/loki:2.9.0
    container_name: loki-server
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki-net

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail-agent
    volumes:
      - ./logs:/var/log/app # Promtail lee exactamente la misma carpeta física mapeada del host
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki-net
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - loki-net

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana-dashboard
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - loki-net
    depends_on:
      - loki
      - prometheus
